"""
Application error codes.

All codes are exactly 9 characters: REC + 3-letter key + 3-digit suffix (001).
"""


class ErrorCodes:
    INTERNAL_SERVER_ERROR = "RECINT001"
    SERVICE_UNAVAILABLE = "RECSVC001"
    INVALID_PARAMS = "RECINV001"
    NOT_FOUND = "RECNOT001"
    DUPLICATE_REQUEST_IN_PROGRESS = "RECDUP001"
    UNAUTHORIZED = "RECUNA001"
    DEACTIVATED = "RECDEA001"
    TOO_MANY_REQUESTS = "RECTOO001"
    SWAGGER_DOC_LOAD_ERROR = "RECDOC001"
    HEALTH_CHECK_FAILED = "RECHEA001"
    BAD_REQUEST = "RECBAD001"
    CONFLICT = "RECCNF001"
    FORBIDDEN = "RECFBD001"
